### ISSUE TITLE
Sorting algorithms implementation umbrella issue

### ISSUE THREAD

**Issue by Youssef1313** [Youssef1313/ds-assignment-1#2]
Each one of us will be assigned one O(n<sup>2</sup>) algorithm and one O(nlogn) algorithm.

### O(n<sup>2</sup>) algorithms

- [x] Selection sort (#3) - Assigned to @mohamed-zayton - PR #22
- [x] Bubble sort (#4) - Assigned to @Youssef1313 - PR #10
- [x] Insertion sort (#5) - Assigned @MOHAND99 - PR #11

### O(nlogn) algorithms

- [x] Merge sort (#6) - Assigned to @MOHAND99 - PR #9
- [x] Heap sort (#7) - Assigned to @Youssef1313 - PR #14
- [x] Quick sort (#8) - Assigned to @mohamed-zayton - PR #21
